name: npm-publish
on:
  push:
    branches:
      - "master"
      - "next"
  pull_request:

jobs:
  test:
    name: "Node ${{ matrix.node }}"
    runs-on: ubuntu-latest
    # Create multiple jobs for each node version
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - run: yarn lint

      - name: Unit tests
        run: yarn test:unit

      - name: Unit tests coverage
      - run: yarn coverage:unit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests # optional
        
  publish-module:
    name: "Publish Module to NPM"
    needs: test
    # publish only when merged in master on original repo, not on PR
    if: github.repository == 'clement-faure/mui-rhf' && (github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}